// <auto-generated />
using CoreGbMSE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreGbMSE.Migrations
{
    [DbContext(typeof(CoreGbMseDbContext))]
    [Migration("20190117125340_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreGbMSE.Data.Filial", b =>
                {
                    b.Property<int>("FilialId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.HasKey("FilialId");

                    b.ToTable("Filials");
                });

            modelBuilder.Entity("CoreGbMSE.Data.Otdel", b =>
                {
                    b.Property<int>("OtdelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.HasKey("OtdelId");

                    b.ToTable("Otdels");
                });

            modelBuilder.Entity("CoreGbMSE.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adress");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OrgName")
                        .IsRequired();

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.Property<string>("WebUrl");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CoreGbMSE.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Doljnost")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("OtdelId");

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.HasKey("StaffId");

                    b.HasIndex("OtdelId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("CoreGbMSE.Models.Staff", b =>
                {
                    b.HasOne("CoreGbMSE.Data.Otdel", "Otdel")
                        .WithMany()
                        .HasForeignKey("OtdelId");
                });
#pragma warning restore 612, 618
        }
    }
}
